<?php
echo '<div class="wps-tab">';
  echo '<h3>Liens utiles</h3>';
  echo '<div class="wps-tab-content-links">';
    echo '<div class="wps-column">';
      echo "<h3>Mon compte</h3>";
      echo "<ul>";
        echo "<li><a href=\"https://www.wpserveur.net/mon-compte/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Connexion</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/mon-compte/lost-password/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Mot de passe oublié</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/themes-plugins-wpserveur/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Plugins et thèmes gratuits</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/mon-compte/orders/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Mes commandes</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/mon-compte/subscriptions/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Mes abonnements</a></li>";
      echo "</ul>";
    echo '</div>';
    echo '<div class="wps-column">';
      echo "<h3>Nos offres</h3>";
      echo "<ul>";
        echo "<li><a href=\"https://www.wpserveur.net/produit/demenagement-installation-wordpress/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Déménagement WordPress</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/produit/changement-dns/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Changement de DNS</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/produit/maintenance-wordpress/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Maintenance WordPress</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/produit/wordpress-pirate-hacke/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Nettoyage & Désinfection</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/comment-passer-a-une-offre-superieure/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Passer au plan supérieur</a></li>";
      echo "</ul>";
    echo '</div>';
    echo '<div class="wps-column">';
      echo "<h3>Articles WPServeur</h3>";
      echo "<ul>";
        echo "<li><a href=\"https://www.wpserveur.net/sauvegardes-wps/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Les sauvegardes WPServeur</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/utilisation-clones/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Utilisation des clones</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/changer-de-nom-de-domaine/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Changement de nom de domaine</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/changement-dns/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Changement des DNS</a></li>";
        echo "<li><a href=\"https://www.wpserveur.net/changer-vos-liens-facilement-avec-srdb/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Changer vos liens facilement avec SRDB</a></li>";
      echo "</ul>";
    echo '</div>';
    echo '<div class="wps-column">';
      echo "<h3>Liens utiles</h3>";
      echo "<ul>";
        echo "<li><a href=\"https://themeforest.net/?ref=wpserver-helper\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Thèmes Premiums WordPress</a></li>";
        echo "<li><a href=\"https://codecanyon.net/?ref=wpserver-helper\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Plugins Premiums WordPress</a></li>";
        echo "<li><a href=\"http://www.elegantthemes.com/affiliates/idevaffiliate.php?id=39389\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Thèmes et Plugins Elegant Theme (Divi, Extra..)</a></li>";
        echo "<li><a href=\"https://wp-child-theme.xyz/\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Générateur de thèmes enfant WordPress</a></li>";
        echo "<li><a href=\"https://wpformation.com\" target=\"blank\"><span class=\"dashicons dashicons-marker\"></span> Articles, tutoriels et formations WordPress</a></li>";
      echo "</ul>";
    echo '</div>';
  echo '</div>';
  echo '<p class="wps-btn-emploi"><a href="https://www.wpserveur.net/mode-emploi-wps/" class="wps-h-btn" target="blank">Voir le mode d\'emploi de WPServeur</a></p>';
echo '</div>';

echo '</div>';
